# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: danger_count.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'danger_count.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64\x61nger_count.proto\x12\x0c\x64\x61nger_count\"\x15\n\x06\x44\x41NGER\x12\x0b\n\x03tag\x18\x01 \x01(\t\"c\n\x06\x44\x61nger\x12\x0b\n\x03UID\x18\x01 \x01(\x03\x12\x16\n\x0ePlayerNickname\x18\x03 \x01(\t\x12\x0e\n\x06region\x18\x05 \x01(\t\x12$\n\x06\x64\x61nger\x18\x16 \x01(\x0b\x32\x14.danger_count.DANGER\";\n\x0e\x44\x61nger_ff_like\x12)\n\x0b\x41\x63\x63ountInfo\x18\x01 \x01(\x0b\x32\x14.danger_count.DANGERb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'danger_count_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DANGER']._serialized_start=36
  _globals['_DANGER']._serialized_end=57
  _globals['_DANGER']._serialized_start=59
  _globals['_DANGER']._serialized_end=158
  _globals['_DANGER_FF_LIKE']._serialized_start=160
  _globals['_DANGER_FF_LIKE']._serialized_end=219
# @@protoc_insertion_point(module_scope)
